// Auto-generated per-family @font-face CSS for PDF export filtering. Do not hand-edit.
const FACES: Record<string, string> = {
  'IBM Plex Serif': '@font-face{font-family:\'IBM Plex Serif\';font-style:italic;font-weight:400;font-display:swap;src:url("/fonts/ibm-plex-serif-400i.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Serif\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/ibm-plex-serif-400.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Serif\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/ibm-plex-serif-600.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Serif\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/ibm-plex-serif-700.woff2") format(\'woff2\');}',
  'Cormorant Garamond': '@font-face{font-family:\'Cormorant Garamond\';font-style:italic;font-weight:500;font-display:swap;src:url("/fonts/cormorant-garamond-500i.woff2") format(\'woff2\');}@font-face{font-family:\'Cormorant Garamond\';font-style:normal;font-weight:500;font-display:swap;src:url("/fonts/cormorant-garamond-500.woff2") format(\'woff2\');}@font-face{font-family:\'Cormorant Garamond\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/cormorant-garamond-600.woff2") format(\'woff2\');}@font-face{font-family:\'Cormorant Garamond\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/cormorant-garamond-700.woff2") format(\'woff2\');}',
  'Public Sans': '@font-face{font-family:\'Public Sans\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/public-sans-400.woff2") format(\'woff2\');}@font-face{font-family:\'Public Sans\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/public-sans-600.woff2") format(\'woff2\');}@font-face{font-family:\'Public Sans\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/public-sans-700.woff2") format(\'woff2\');}@font-face{font-family:\'Public Sans\';font-style:normal;font-weight:800;font-display:swap;src:url("/fonts/public-sans-800.woff2") format(\'woff2\');}',
  'Space Grotesk': '@font-face{font-family:\'Space Grotesk\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/space-grotesk-400.woff2") format(\'woff2\');}@font-face{font-family:\'Space Grotesk\';font-style:normal;font-weight:500;font-display:swap;src:url("/fonts/space-grotesk-500.woff2") format(\'woff2\');}@font-face{font-family:\'Space Grotesk\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/space-grotesk-600.woff2") format(\'woff2\');}@font-face{font-family:\'Space Grotesk\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/space-grotesk-700.woff2") format(\'woff2\');}',
  'Fraunces': '@font-face{font-family:\'Fraunces\';font-style:italic;font-weight:400;font-display:swap;src:url("/fonts/fraunces-400i.woff2") format(\'woff2\');}@font-face{font-family:\'Fraunces\';font-style:italic;font-weight:600;font-display:swap;src:url("/fonts/fraunces-600i.woff2") format(\'woff2\');}@font-face{font-family:\'Fraunces\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/fraunces-400.woff2") format(\'woff2\');}@font-face{font-family:\'Fraunces\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/fraunces-600.woff2") format(\'woff2\');}@font-face{font-family:\'Fraunces\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/fraunces-700.woff2") format(\'woff2\');}@font-face{font-family:\'Fraunces\';font-style:normal;font-weight:900;font-display:swap;src:url("/fonts/fraunces-900.woff2") format(\'woff2\');}',
  'JetBrains Mono': '@font-face{font-family:\'JetBrains Mono\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/jetbrains-mono-400.woff2") format(\'woff2\');}@font-face{font-family:\'JetBrains Mono\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/jetbrains-mono-600.woff2") format(\'woff2\');}@font-face{font-family:\'JetBrains Mono\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/jetbrains-mono-700.woff2") format(\'woff2\');}',
  'Playfair Display': '@font-face{font-family:\'Playfair Display\';font-style:italic;font-weight:600;font-display:swap;src:url("/fonts/playfair-display-600i.woff2") format(\'woff2\');}@font-face{font-family:\'Playfair Display\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/playfair-display-600.woff2") format(\'woff2\');}@font-face{font-family:\'Playfair Display\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/playfair-display-700.woff2") format(\'woff2\');}@font-face{font-family:\'Playfair Display\';font-style:normal;font-weight:800;font-display:swap;src:url("/fonts/playfair-display-800.woff2") format(\'woff2\');}',
  'IBM Plex Mono': '@font-face{font-family:\'IBM Plex Mono\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/ibm-plex-mono-400.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Mono\';font-style:normal;font-weight:500;font-display:swap;src:url("/fonts/ibm-plex-mono-500.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Mono\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/ibm-plex-mono-600.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Mono\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/ibm-plex-mono-700.woff2") format(\'woff2\');}',
  'Libre Caslon Text': '@font-face{font-family:\'Libre Caslon Text\';font-style:italic;font-weight:400;font-display:swap;src:url("/fonts/libre-caslon-text-400i.woff2") format(\'woff2\');}@font-face{font-family:\'Libre Caslon Text\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/libre-caslon-text-400.woff2") format(\'woff2\');}@font-face{font-family:\'Libre Caslon Text\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/libre-caslon-text-700.woff2") format(\'woff2\');}',
  'Source Serif 4': '@font-face{font-family:\'Source Serif 4\';font-style:italic;font-weight:400;font-display:swap;src:url("/fonts/source-serif-4-400i.woff2") format(\'woff2\');}@font-face{font-family:\'Source Serif 4\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/source-serif-4-400.woff2") format(\'woff2\');}@font-face{font-family:\'Source Serif 4\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/source-serif-4-600.woff2") format(\'woff2\');}@font-face{font-family:\'Source Serif 4\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/source-serif-4-700.woff2") format(\'woff2\');}',
  'Atkinson Hyperlegible': '@font-face{font-family:\'Atkinson Hyperlegible\';font-style:italic;font-weight:400;font-display:swap;src:url("/fonts/atkinson-hyperlegible-400i.woff2") format(\'woff2\');}@font-face{font-family:\'Atkinson Hyperlegible\';font-style:italic;font-weight:700;font-display:swap;src:url("/fonts/atkinson-hyperlegible-700i.woff2") format(\'woff2\');}@font-face{font-family:\'Atkinson Hyperlegible\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/atkinson-hyperlegible-400.woff2") format(\'woff2\');}@font-face{font-family:\'Atkinson Hyperlegible\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/atkinson-hyperlegible-700.woff2") format(\'woff2\');}',
  'IBM Plex Sans': '@font-face{font-family:\'IBM Plex Sans\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/ibm-plex-sans-400.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Sans\';font-style:normal;font-weight:500;font-display:swap;src:url("/fonts/ibm-plex-sans-500.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Sans\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/ibm-plex-sans-600.woff2") format(\'woff2\');}@font-face{font-family:\'IBM Plex Sans\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/ibm-plex-sans-700.woff2") format(\'woff2\');}',
  'Caveat': '@font-face{font-family:\'Caveat\';font-style:normal;font-weight:500;font-display:swap;src:url("/fonts/caveat-500.woff2") format(\'woff2\');}@font-face{font-family:\'Caveat\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/caveat-600.woff2") format(\'woff2\');}@font-face{font-family:\'Caveat\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/caveat-700.woff2") format(\'woff2\');}',
  'Archivo': '@font-face{font-family:\'Archivo\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/archivo-400.woff2") format(\'woff2\');}@font-face{font-family:\'Archivo\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/archivo-600.woff2") format(\'woff2\');}@font-face{font-family:\'Archivo\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/archivo-700.woff2") format(\'woff2\');}@font-face{font-family:\'Archivo\';font-style:normal;font-weight:800;font-display:swap;src:url("/fonts/archivo-800.woff2") format(\'woff2\');}@font-face{font-family:\'Archivo\';font-style:normal;font-weight:900;font-display:swap;src:url("/fonts/archivo-900.woff2") format(\'woff2\');}',
  'Source Sans 3': '@font-face{font-family:\'Source Sans 3\';font-style:italic;font-weight:400;font-display:swap;src:url("/fonts/source-sans-3-400i.woff2") format(\'woff2\');}@font-face{font-family:\'Source Sans 3\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/source-sans-3-400.woff2") format(\'woff2\');}@font-face{font-family:\'Source Sans 3\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/source-sans-3-600.woff2") format(\'woff2\');}@font-face{font-family:\'Source Sans 3\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/source-sans-3-700.woff2") format(\'woff2\');}',
  'Inter': '@font-face{font-family:\'Inter\';font-style:normal;font-weight:400;font-display:swap;src:url("/fonts/inter-400.woff2") format(\'woff2\');}@font-face{font-family:\'Inter\';font-style:normal;font-weight:500;font-display:swap;src:url("/fonts/inter-500.woff2") format(\'woff2\');}@font-face{font-family:\'Inter\';font-style:normal;font-weight:600;font-display:swap;src:url("/fonts/inter-600.woff2") format(\'woff2\');}@font-face{font-family:\'Inter\';font-style:normal;font-weight:700;font-display:swap;src:url("/fonts/inter-700.woff2") format(\'woff2\');}@font-face{font-family:\'Inter\';font-style:normal;font-weight:800;font-display:swap;src:url("/fonts/inter-800.woff2") format(\'woff2\');}',
};

// Sample documents use Office-native families. Keep those names available in
// preview/PDF by serving the closest bundled face, while DOCX continues to
// retain the familiar sample family names.
for (const [alias, source] of Object.entries({
  Aptos: "Public Sans",
  "Aptos Display": "Public Sans",
  Arial: "IBM Plex Sans",
  Calibri: "Source Sans 3",
  "Bell MT": "Cormorant Garamond",
  "Book Antiqua": "Libre Caslon Text",
  "Times New Roman": "Source Serif 4",
})) {
  const css = FACES[source];
  if (css) FACES[alias] = css.replaceAll(source, alias);
}

export function fontFaceCssFor(families: readonly string[]): string {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const family of families) {
    const base = family.split(",")[0].trim().replace(/^['"]+|['"]+$/g, "");
    if (!base || seen.has(base)) continue;
    seen.add(base);
    const css = FACES[base];
    if (css) out.push(css);
  }
  return out.join("");
}

export const DOCUMENT_FONT_FAMILIES = Object.keys(FACES);

/** All self-hosted OFL document fonts, injected via a <style> tag in the root layout. */
export const DOCUMENT_FONT_FACE_CSS_ALL = Object.values(FACES).join("");
