import type {
  DocumentLayoutId, DocumentThemeOverrides, DocumentTemplateId, DocumentTemplateAliasId,
  DocumentThemePalette, DocumentTypography, LogoScale, LogoPosition, Policy, SdgDisplayMode,
  StandardSectionKind, TemplateBrandOverrides, TemplateComposition, ThemeBackground, ThemeDensity, VisualStyle,
} from "./types";
import { normalizePageBorder } from "./page-geometry";
import type { PageBorder } from "./types";
import type { CoverMotifScene } from "./cover-motifs";
import { normalizeLogoPalette } from "./logo-palette";

export type { DocumentTemplateId, TemplateBrandOverrides, TemplateComposition };
export type UniversalTemplateId = DocumentTemplateId;
export type UniversalTemplateDefinition = DocumentThemeDefinition;
export type DocumentThemeColors = DocumentThemePalette;
export type DocumentSectionKind = StandardSectionKind | "custom";
export type DocumentThemeFamily = "Policy Pack" | "Executive" | "Controlled" | "Governance" | "Operations" | "Sustainability" | "People" | "Metrics";
export type UniversalTemplateFamily = "Standard" | "Executive" | "Controlled" | "Governance" | "Operations" | "Sustainability" | "People" | "Metrics";
export type DocumentThemeIntent = "minimal" | "corporate" | "regulatory" | "editorial" | "impact" | "data-heavy" | "research";
export type DocumentSectionRecipe = "charter-narrative" | "charter-ledger" | "charter-mosaic" | "dossier-narrative" | "dossier-columns" | "dossier-ledger" | "atlas-statement" | "atlas-modules" | "atlas-bands" | "atlas-mosaic" | "journal-narrative" | "journal-entries" | "journal-ledger";
// Cover scenes share the motif inventory so sample-derived artwork can flow
// through the same theme and renderer contracts as the legacy scenes.
export type CoverScene = CoverMotifScene;
export type ContentsScene = "dotted-leaders" | "rail-index" | "tile-index" | "editorial-index";
export type PageZone = "single-folio" | "numbered-rail" | "modular-grid" | "editorial-margin";
export type DocumentControlTreatment = "cover-metadata" | "control-panel" | "approval-record" | "footer-register";
type DocumentThemePolicyInput = Pick<Policy, "documentTemplate" | "documentTheme" | "documentThemeOverrides" | "templateBrandOverrides"> & Partial<Pick<Policy, "brandColorSource" | "company">>;

export type DocumentThemeLayout = {
  layoutId: DocumentLayoutId;
  professionalVariant?: "corporate" | "editorial" | "governance" | "minimal" | "sustainability" | "institutional";
  archetype: "heritage-charter" | "boardroom-dossier" | "impact-atlas" | "field-journal" | "universal-composition";
  bestFor: string; descriptors: readonly [string, string, string]; cover: CoverScene; toc: ContentsScene; pageFrame: PageZone;
  sectionOpener: "formal-ordinal" | "dossier-label" | "statement-band" | "chapter-number" | "clause-number" | "agenda-label" | "memo-rule" | "spec-ordinal" | "finding-band";
  bodyGrid: "narrow-single" | "rail-content" | "adaptive-modules" | "margin-led" | "swiss-grid" | "ledger-columns" | "scorecard-stack";
  dataLayout: "formal-grid" | "compact-ledger" | "target-bands" | "quiet-rules" | "scorecard-bands" | "ledger-trails" | "evidence-matrix" | "spec-table";
  acknowledgement: "legal-form" | "approval-block" | "signature-panel" | "affidavit" | "approval-stamp" | "decision-record" | "conclusion-panel";
  controlTreatment: DocumentControlTreatment; runningFurniture: "centered-folio" | "breadcrumb-bar" | "edge-folio" | "outer-folio" | "traceability-rail" | "clause-folio";
  motif: CoverMotifScene; imageTreatment: "none" | "restrained-cover" | "full-bleed-cover" | "section-led"; sectionRecipes: Record<DocumentSectionKind, DocumentSectionRecipe>;
};
export type DocumentThemeDefinition = {
  collection?: "professional"; id: DocumentTemplateId; name: string; description: string; family: DocumentThemeFamily; universalFamily: UniversalTemplateFamily; intent: DocumentThemeIntent; sourceReferences?: readonly string[];
  tags: readonly string[]; imageSupport: readonly ("cover" | "section")[]; previewRecipe: string; structuralSignature: string; compositionFingerprint: string; composition: TemplateComposition; colors: DocumentThemePalette; layout: DocumentThemeLayout;
  defaults: { typography: DocumentTypography; visualStyle: VisualStyle; logoPosition: LogoPosition; sdgDisplay: SdgDisplayMode; density: ThemeDensity };
};
export type ResolvedDocumentThemeDefinition = DocumentThemeDefinition & { pageBorder: PageBorder; customThemeName?: string; background: ThemeBackground; density: ThemeDensity; logoScale: LogoScale };

export const LOGO_SCALE_MIN = 50;
export const LOGO_SCALE_MAX = 180;
export const LOGO_SCALE_DEFAULT = 100;

export function logoScalePercent(value?: LogoScale): number {
  if (typeof value === "number" && Number.isFinite(value)) return Math.min(LOGO_SCALE_MAX, Math.max(LOGO_SCALE_MIN, Math.round(value)));
  if (value === "small") return 72;
  if (value === "large") return 128;
  return LOGO_SCALE_DEFAULT;
}

export function logoScaleFactor(value?: LogoScale): number {
  return logoScalePercent(value) / 100;
}

export function runningLogoFit(value?: LogoScale) {
  const factor = logoScaleFactor(value);
  return {
    widthMm: 28 * factor,
    heightMm: 8 * factor,
    widthPx: Math.round(106 * factor),
    heightPx: Math.round(30 * factor),
  };
}

/** Persisted IDs are accepted only here. They are never catalog entries or active theme definitions. */
export const LEGACY_DOCUMENT_THEME_UPGRADES: Record<DocumentTemplateAliasId, DocumentTemplateId> = {
  "corporate-standard-v1": "standard-pack", "plain-standard": "standard-pack", "accessible-standard": "standard-pack", "executive-editorial-v1": "executive-brief", "board-paper": "executive-brief", "leadership-memo": "executive-brief",
  "governance-manual-v1": "controlled-manual", "governance-manual": "controlled-manual", "compliance-policy": "controlled-manual", "audit-dossier": "controlled-manual", "legal-register": "governance-register", "research-paper": "governance-register", "technical-standard": "governance-register", "evidence-review": "governance-register",
  "modern-minimal-v1": "operations-guide", "modern-standard": "operations-guide", "monochrome-grid": "operations-guide", "sustainability-report-v1": "sustainability-charter", "sustainability-report": "sustainability-charter", "outcome-impact": "sustainability-charter",
  "community-brief": "people-charter", "editorial-report": "people-charter", "magazine-policy": "people-charter", "institutional-classic-v1": "people-charter", "public-sector-standard": "people-charter", "institutional-report": "people-charter", "field-report": "people-charter", "kpi-report": "metrics-ledger", "performance-review": "metrics-ledger",
  "evergreen-heritage": "controlled-manual", "executive-navy": "executive-brief", "modern-teal": "sustainability-charter", "earth-editorial": "people-charter", "sdg-impact": "sustainability-charter",
};
export const UNIVERSAL_TEMPLATE_ALIASES: Record<string, DocumentTemplateId> = { "sdg-impact": "sustainability-charter" };
export const DEFAULT_DOCUMENT_THEME_ID: DocumentTemplateId = "standard-pack";
export const DEFAULT_DOCUMENT_TEMPLATE_ID: DocumentTemplateId = DEFAULT_DOCUMENT_THEME_ID;

const RECIPES = {
  charter: { preface: "charter-narrative", declaration: "charter-narrative", scope: "charter-narrative", definitions: "charter-narrative", focus: "charter-ledger", qualitative: "charter-ledger", quantitative: "charter-mosaic", sdg: "charter-mosaic", responsibilities: "charter-ledger", monitoring: "charter-narrative", review: "charter-narrative", revision: "charter-mosaic", custom: "charter-ledger" },
  dossier: { preface: "dossier-narrative", declaration: "dossier-narrative", scope: "dossier-narrative", definitions: "dossier-narrative", focus: "dossier-columns", qualitative: "dossier-columns", quantitative: "dossier-ledger", sdg: "dossier-columns", responsibilities: "dossier-columns", monitoring: "dossier-narrative", review: "dossier-narrative", revision: "dossier-ledger", custom: "dossier-columns" },
  atlas: { preface: "atlas-statement", declaration: "atlas-statement", scope: "atlas-statement", definitions: "atlas-statement", focus: "atlas-modules", qualitative: "atlas-modules", quantitative: "atlas-bands", sdg: "atlas-mosaic", responsibilities: "atlas-modules", monitoring: "atlas-statement", review: "atlas-statement", revision: "atlas-bands", custom: "atlas-modules" },
  journal: { preface: "journal-narrative", declaration: "journal-narrative", scope: "journal-narrative", definitions: "journal-narrative", focus: "journal-entries", qualitative: "journal-entries", quantitative: "journal-ledger", sdg: "journal-entries", responsibilities: "journal-entries", monitoring: "journal-narrative", review: "journal-narrative", revision: "journal-ledger", custom: "journal-entries" },
} satisfies Record<string, Record<DocumentSectionKind, DocumentSectionRecipe>>;

const fonts = {
  standard: { fontFamily: "Source Sans 3", headingFontFamily: "Source Serif 4", headingSize: 16, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.45 }, executive: { fontFamily: "IBM Plex Sans", headingFontFamily: "IBM Plex Serif", headingSize: 16, subheadingSize: 13, paragraphSize: 10.5, lineSpacing: 1.3 }, controlled: { fontFamily: "Public Sans", headingFontFamily: "Archivo", headingSize: 15, subheadingSize: 12, paragraphSize: 10.5, lineSpacing: 1.35 }, governance: { fontFamily: "Source Sans 3", headingFontFamily: "Archivo", headingSize: 15, subheadingSize: 12, paragraphSize: 10.5, lineSpacing: 1.35 }, operations: { fontFamily: "Source Sans 3", headingFontFamily: "IBM Plex Sans", headingSize: 16, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.4 }, sustainability: { fontFamily: "Inter", headingFontFamily: "Fraunces", headingSize: 17, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.45 }, people: { fontFamily: "Public Sans", headingFontFamily: "Fraunces", headingSize: 17, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.5 }, metrics: { fontFamily: "IBM Plex Mono", headingFontFamily: "IBM Plex Sans", headingSize: 15, subheadingSize: 12, paragraphSize: 10, lineSpacing: 1.3 },
} satisfies Record<string, DocumentTypography>;
const palette = (primary: string, primaryDark: string, soft: string, paper: string, ink: string, muted: string, line: string, accent: string): DocumentThemePalette => ({ primary, primaryDark, subheading: primaryDark, soft, paper, ink, muted, line, accent, onPrimary: "#FFFFFF" });

const SAMPLE_VARIANT_BY_LAYOUT: Record<DocumentLayoutId, NonNullable<DocumentThemeLayout["professionalVariant"]>> = {
  "clean-essentials": "minimal", executive: "governance", governance: "corporate", institutional: "institutional",
  editorial: "minimal", impact: "sustainability", data: "governance", technical: "editorial",
};
function makeLayout(input: { layoutId: DocumentLayoutId; bestFor: string; descriptors: readonly [string, string, string]; cover: CoverScene; toc: ContentsScene; pageFrame: PageZone; sectionOpener: DocumentThemeLayout["sectionOpener"]; bodyGrid: DocumentThemeLayout["bodyGrid"]; dataLayout: DocumentThemeLayout["dataLayout"]; acknowledgement: DocumentThemeLayout["acknowledgement"]; controlTreatment: DocumentControlTreatment; runningFurniture: DocumentThemeLayout["runningFurniture"]; motif: CoverMotifScene; imageTreatment: DocumentThemeLayout["imageTreatment"]; recipes: keyof typeof RECIPES }): DocumentThemeLayout {
  return { layoutId: input.layoutId, professionalVariant: SAMPLE_VARIANT_BY_LAYOUT[input.layoutId], archetype: "universal-composition", bestFor: input.bestFor, descriptors: input.descriptors, cover: input.cover, toc: input.toc, pageFrame: input.pageFrame, sectionOpener: input.sectionOpener, bodyGrid: input.bodyGrid, dataLayout: input.dataLayout, acknowledgement: input.acknowledgement, controlTreatment: input.controlTreatment, runningFurniture: input.runningFurniture, motif: input.motif, imageTreatment: input.imageTreatment, sectionRecipes: RECIPES[input.recipes] };
}
type ThemeSpec = Omit<DocumentThemeDefinition, "structuralSignature" | "compositionFingerprint" | "composition">;
const theme = (spec: ThemeSpec): DocumentThemeDefinition => {
  const structuralSignature = [spec.layout.layoutId, spec.layout.cover, spec.layout.toc, spec.layout.pageFrame, spec.layout.sectionOpener, spec.layout.bodyGrid, spec.layout.dataLayout, spec.layout.acknowledgement, spec.layout.controlTreatment, spec.layout.runningFurniture, spec.layout.motif, spec.layout.imageTreatment, spec.defaults.density].join("|");
  const composition: TemplateComposition = { coverScene: `${spec.id}:cover:${spec.layout.cover}`, contentsScene: `${spec.id}:contents:${spec.layout.toc}`, pageZones: `${spec.id}:zones:${spec.layout.pageFrame}:${spec.layout.bodyGrid}`, sectionHeading: `${spec.id}:heading:${spec.layout.sectionOpener}`, narrativeTreatment: `${spec.id}:narrative:${spec.layout.bodyGrid}`, listTreatment: `${spec.id}:list:${spec.layout.bodyGrid}`, targetTreatment: `${spec.id}:targets:${spec.layout.dataLayout}`, tableTreatment: `${spec.id}:tables:${spec.layout.dataLayout}`, runningFurniture: `${spec.id}:furniture:${spec.layout.runningFurniture}`, approvalTreatment: `${spec.id}:approval:${spec.layout.acknowledgement}`, controlTreatment: `${spec.id}:controls:${spec.layout.controlTreatment}`, imageSlots: [...spec.imageSupport], fallbackArtwork: `${spec.id}:artwork:${spec.layout.motif}`, densityRule: spec.defaults.density, overflowRule: `${spec.id}:overflow:print-safe-a4-keep-with-next` };
  return { ...spec, structuralSignature, compositionFingerprint: [composition.coverScene, composition.contentsScene, composition.pageZones, composition.sectionHeading, composition.targetTreatment, composition.tableTreatment, composition.controlTreatment, composition.imageSlots.join("+") || "imageless", composition.densityRule].join("|"), composition };
};
const sharedTags = ["universal", "source-informed", "policy-agnostic"] as const;
const base = (id: DocumentTemplateId, name: string, description: string, family: DocumentThemeFamily, universalFamily: UniversalTemplateFamily, intent: DocumentThemeIntent, tags: readonly string[], imageSupport: readonly ("cover" | "section")[], colors: DocumentThemePalette, layout: DocumentThemeLayout, typography: DocumentTypography, visualStyle: VisualStyle, logoPosition: LogoPosition, sdgDisplay: SdgDisplayMode, density: ThemeDensity, sourceReferences: readonly string[]): ThemeSpec => ({ collection: "professional", id, name, description, family, universalFamily, intent, sourceReferences, tags: [...sharedTags, ...tags], imageSupport, previewRecipe: `${name}: source-matched cover, contents, body, targets, controls, and approval treatment`, colors, layout, defaults: { typography, visualStyle, logoPosition, sdgDisplay, density } });

/** New active designs distilled from the project sample corpus; source identity and wording are never embedded. */
const DOCUMENT_THEME_FONT_DEFAULTS: Record<string, DocumentTypography> = {
  "standard-pack": { fontFamily: "Source Sans 3", headingFontFamily: "Source Serif 4", headingSize: 16, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.45 },
  "executive-brief": { fontFamily: "IBM Plex Sans", headingFontFamily: "IBM Plex Serif", headingSize: 16, subheadingSize: 13, paragraphSize: 10.5, lineSpacing: 1.3 },
  "controlled-manual": { fontFamily: "Public Sans", headingFontFamily: "Archivo", headingSize: 15, subheadingSize: 12, paragraphSize: 10.5, lineSpacing: 1.35 },
  "governance-register": { fontFamily: "Inter", headingFontFamily: "Playfair Display", headingSize: 15, subheadingSize: 12, paragraphSize: 11, lineSpacing: 1.4 },
  "operations-guide": { fontFamily: "Atkinson Hyperlegible", headingFontFamily: "Space Grotesk", headingSize: 15, subheadingSize: 12, paragraphSize: 10, lineSpacing: 1.3 },
  "sustainability-charter": { fontFamily: "Libre Caslon Text", headingFontFamily: "Fraunces", headingSize: 17, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.45 },
  "people-charter": { fontFamily: "Cormorant Garamond", headingFontFamily: "Source Serif 4", headingSize: 17, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.5 },
  "metrics-ledger": { fontFamily: "IBM Plex Mono", headingFontFamily: "IBM Plex Sans", headingSize: 15, subheadingSize: 12, paragraphSize: 9.5, lineSpacing: 1.25 },
};

export const DOCUMENT_THEMES: readonly DocumentThemeDefinition[] = [
  theme(base("standard-pack", "Quiet Aptos Policy", "A clean source-matched policy page with generous white space, plain numbering, and a small document-control footer.", "Policy Pack", "Standard", "minimal", ["Aptos body", "quiet cover", "plain numbering"], ["section"], palette("#173F4B", "#102B33", "#EAF2F3", "#FFFFFF", "#192529", "#66757A", "#D6E0E2", "#C7833A"), makeLayout({ layoutId: "clean-essentials", bestFor: "Clear internal policies with a calm, readable page", descriptors: ["Quiet", "Readable", "Aptos"], cover: "sample-quiet-title", toc: "dotted-leaders", pageFrame: "single-folio", sectionOpener: "formal-ordinal", bodyGrid: "narrow-single", dataLayout: "formal-grid", acknowledgement: "legal-form", controlTreatment: "cover-metadata", runningFurniture: "centered-folio", motif: "sample-quiet-title", imageTreatment: "section-led", recipes: "charter" }), { fontFamily: "Public Sans", headingFontFamily: "Public Sans", headingSize: 16, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.45 }, "corporate", "left", "names", "balanced", ["CTX Environmental Policy", "Naxpar Environmental Policy", "Yash Environmental Policy"])),
  theme(base("executive-brief", "Controlled Approval Sheet", "A controlled title page with a compact metadata grid, approval fields, and a strong revision line.", "Executive", "Executive", "regulatory", ["approval grid", "revision line", "controlled copy"], [], palette("#183A5A", "#102840", "#EAF1F8", "#FFFFFF", "#1C2732", "#657585", "#D1DCE8", "#B77A36"), makeLayout({ layoutId: "executive", bestFor: "Policies requiring visible owner, approver, and revision information", descriptors: ["Controlled", "Compact", "Approver-ready"], cover: "sample-control-grid", toc: "rail-index", pageFrame: "numbered-rail", sectionOpener: "dossier-label", bodyGrid: "rail-content", dataLayout: "compact-ledger", acknowledgement: "approval-block", controlTreatment: "approval-record", runningFurniture: "breadcrumb-bar", motif: "sample-control-grid", imageTreatment: "none", recipes: "dossier" }), { fontFamily: "Arial", headingFontFamily: "Arial", headingSize: 16, subheadingSize: 13, paragraphSize: 10.5, lineSpacing: 1.3 }, "corporate", "left", "names", "compact", ["Yash Environmental Policy", "Yash Ethics Policy", "Yash Supply Chain Policy"])),
  theme(base("controlled-manual", "Table Register", "A table-first policy layout with clear column rules, indexed clauses, and dense but readable evidence blocks.", "Controlled", "Controlled", "data-heavy", ["table first", "column rules", "evidence blocks"], [], palette("#26323D", "#18232B", "#EEF1F3", "#FFFFFF", "#1D252B", "#69747B", "#D8DEE2", "#9A6A36"), makeLayout({ layoutId: "governance", bestFor: "Evidence-heavy policies and standard packs with repeated tables", descriptors: ["Tabular", "Auditable", "Dense"], cover: "sample-table-ledger", toc: "tile-index", pageFrame: "numbered-rail", sectionOpener: "clause-number", bodyGrid: "ledger-columns", dataLayout: "evidence-matrix", acknowledgement: "approval-stamp", controlTreatment: "control-panel", runningFurniture: "traceability-rail", motif: "sample-table-ledger", imageTreatment: "none", recipes: "dossier" }), { fontFamily: "Arial", headingFontFamily: "Arial", headingSize: 15, subheadingSize: 12, paragraphSize: 10.5, lineSpacing: 1.35 }, "corporate", "left", "names", "compact", ["Quality Rubbers Environmental Policy", "Prestige Promotion Labour Policy", "20 Microns ESG Policy Manual"])),
  theme(base("governance-register", "Framework Map", "A structured framework format with connected responsibilities, numbered sections, and a formal review record.", "Governance", "Governance", "regulatory", ["framework map", "responsibility", "review record"], [], palette("#315145", "#20372F", "#EAF2ED", "#FFFEFB", "#1D2822", "#6C776F", "#D5E0D8", "#A16D37"), makeLayout({ layoutId: "institutional", bestFor: "Frameworks and governance documents with explicit structure", descriptors: ["Structured", "Framework", "Assignable"], cover: "sample-framework-map", toc: "dotted-leaders", pageFrame: "single-folio", sectionOpener: "clause-number", bodyGrid: "narrow-single", dataLayout: "spec-table", acknowledgement: "decision-record", controlTreatment: "control-panel", runningFurniture: "clause-folio", motif: "sample-framework-map", imageTreatment: "none", recipes: "charter" }), { fontFamily: "Calibri", headingFontFamily: "Calibri", headingSize: 15, subheadingSize: 12, paragraphSize: 11, lineSpacing: 1.4 }, "corporate", "left", "names", "balanced", ["Anthea Responsible Business Conduct Framework", "Anthea Responsible Workforce Framework", "Anthea Sustainable Supply Chain Framework"])),
  theme(base("operations-guide", "Compact Operating Standard", "A compact operating page with a narrow title band, practical sections, and minimal running furniture.", "Operations", "Operations", "minimal", ["compact strip", "operating page", "practical"], ["section"], palette("#3A4C56", "#24333A", "#EDF2F4", "#FFFFFF", "#20282D", "#6A767B", "#D8E0E3", "#C07D35"), makeLayout({ layoutId: "editorial", bestFor: "Short operating policies and site guidance", descriptors: ["Compact", "Practical", "Light"], cover: "sample-compact-strip", toc: "rail-index", pageFrame: "modular-grid", sectionOpener: "agenda-label", bodyGrid: "adaptive-modules", dataLayout: "quiet-rules", acknowledgement: "conclusion-panel", controlTreatment: "footer-register", runningFurniture: "edge-folio", motif: "sample-compact-strip", imageTreatment: "section-led", recipes: "journal" }), { fontFamily: "Arial", headingFontFamily: "Arial", headingSize: 15, subheadingSize: 12, paragraphSize: 10, lineSpacing: 1.3 }, "corporate", "left", "names", "balanced", ["Mewburn Environmental Policy", "Shilpa Medicare Environmental Policy", "Renewsys Green Policy"])),
  theme(base("sustainability-charter", "Image Led Charter", "An image-led sustainability page with a restrained color band, narrative opening, and visible commitments.", "Sustainability", "Sustainability", "impact", ["image-led", "narrative opening", "commitments"], ["cover", "section"], palette("#2D685A", "#1B443A", "#E5F1EC", "#FFFFFF", "#1D2925", "#64766E", "#CFE0D9", "#B87834"), makeLayout({ layoutId: "impact", bestFor: "Sustainability policies with imagery and narrative commitments", descriptors: ["Image-led", "Narrative", "Calm"], cover: "sample-editorial-image", toc: "tile-index", pageFrame: "modular-grid", sectionOpener: "statement-band", bodyGrid: "adaptive-modules", dataLayout: "target-bands", acknowledgement: "signature-panel", controlTreatment: "cover-metadata", runningFurniture: "edge-folio", motif: "sample-editorial-image", imageTreatment: "restrained-cover", recipes: "atlas" }), { fontFamily: "Bell MT", headingFontFamily: "Bell MT", headingSize: 17, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.45 }, "modern", "left", "tiles", "spacious", ["Ganges Environmental Policy", "Ganges Social Policy", "KBL Cosmetic Environmental Policy"])),
  theme(base("people-charter", "Heritage Crest Policy", "A formal heritage presentation with centered title hierarchy, crest-like artwork, and warm serif typography.", "People", "People", "editorial", ["serif hierarchy", "crest", "people-facing"], ["cover", "section"], palette("#5E443A", "#3C2B25", "#F3EAE4", "#FFFDFC", "#2B221E", "#796B63", "#E2D5CE", "#2F6B61"), makeLayout({ layoutId: "technical", bestFor: "People-facing policies that need a formal, established voice", descriptors: ["Heritage", "Serif", "Formal"], cover: "sample-heritage-crest", toc: "dotted-leaders", pageFrame: "editorial-margin", sectionOpener: "statement-band", bodyGrid: "margin-led", dataLayout: "target-bands", acknowledgement: "signature-panel", controlTreatment: "cover-metadata", runningFurniture: "centered-folio", motif: "sample-heritage-crest", imageTreatment: "section-led", recipes: "charter" }), { fontFamily: "Book Antiqua", headingFontFamily: "Book Antiqua", headingSize: 17, subheadingSize: 13, paragraphSize: 11, lineSpacing: 1.5 }, "modern", "center", "tiles", "spacious", ["Sri All India Environmental Policy", "Sri All India Labour Policy", "Sri All India Ethics Policy"])),
  theme(base("metrics-ledger", "IMS Operating Tabs", "A compact integrated-management format with tabbed navigation, small body text, and strong traceability.", "Metrics", "Metrics", "data-heavy", ["IMS tabs", "traceability", "small measure"], [], palette("#244B59", "#17343E", "#E8F0F2", "#FFFFFF", "#18262C", "#65757B", "#CFDDE1", "#B77935"), makeLayout({ layoutId: "data", bestFor: "Dense operating systems, registers, and review trails", descriptors: ["Tabbed", "Traceable", "Compact"], cover: "sample-operating-tabs", toc: "rail-index", pageFrame: "modular-grid", sectionOpener: "spec-ordinal", bodyGrid: "ledger-columns", dataLayout: "ledger-trails", acknowledgement: "approval-block", controlTreatment: "control-panel", runningFurniture: "traceability-rail", motif: "sample-operating-tabs", imageTreatment: "none", recipes: "dossier" }), { fontFamily: "Times New Roman", headingFontFamily: "Times New Roman", headingSize: 15, subheadingSize: 12, paragraphSize: 9.5, lineSpacing: 1.25 }, "corporate", "left", "names", "compact", ["Renewsys Corporate Governance and Ethics Policy", "Renewsys Workplace Rights Policy", "Renewsys Green Supply Chain Policy"])),
].map((item) => ({
  ...item,
  defaults: {
    ...item.defaults,
    typography: DOCUMENT_THEME_FONT_DEFAULTS[item.id] || item.defaults.typography,
  },
}));

export const UNIVERSAL_TEMPLATES = DOCUMENT_THEMES;
export const DOCUMENT_TEMPLATES = DOCUMENT_THEMES;
const DOCUMENT_THEME_MAP = new Map(DOCUMENT_THEMES.map((item) => [item.id, item]));
export function upgradeDocumentThemeId(id?: string | null): DocumentTemplateId { if (!id) return DEFAULT_DOCUMENT_THEME_ID; if (id in LEGACY_DOCUMENT_THEME_UPGRADES) return LEGACY_DOCUMENT_THEME_UPGRADES[id as DocumentTemplateAliasId]; if (id in UNIVERSAL_TEMPLATE_ALIASES) return UNIVERSAL_TEMPLATE_ALIASES[id]; return DOCUMENT_THEME_MAP.has(id as DocumentTemplateId) ? (id as DocumentTemplateId) : DEFAULT_DOCUMENT_THEME_ID; }
export const upgradeDocumentTemplateId = upgradeDocumentThemeId;
export function resolveDocumentTemplateId(policy: Pick<Policy, "documentTemplate" | "documentTheme">): DocumentTemplateId { return upgradeDocumentThemeId(policy.documentTemplate ?? policy.documentTheme); }
export function getDocumentTheme(id?: string | null): DocumentThemeDefinition { return DOCUMENT_THEME_MAP.get(upgradeDocumentThemeId(id)) || DOCUMENT_THEMES[0]; }
export const getDocumentTemplate = getDocumentTheme;
export function getPolicyDocumentTheme(policy: DocumentThemePolicyInput): ResolvedDocumentThemeDefinition { const base = getDocumentTheme(resolveDocumentTemplateId(policy)); const rawOverrides = (policy as Policy).templateBrandOverrides ?? policy.documentThemeOverrides; const overrides = normalizeDocumentThemeOverrides(rawOverrides); const logoColors = policy.brandColorSource === "template" ? undefined : normalizeLogoPalette(policy.company?.logoPalette); const logoThemeColors = logoColors ? { ...logoColors, subheading: logoColors.primaryDark, ink: logoColors.primaryDark, muted: blendHex(logoColors.primaryDark, base.colors.paper, .48), line: blendHex(logoColors.primary, base.colors.paper, .78) } : undefined; return { ...base, pageBorder: normalizePageBorder(overrides.pageBorder), customThemeName: overrides.customThemeName, colors: { ...base.colors, ...logoThemeColors, ...overrides.colors }, background: overrides.background || defaultThemeBackground(base), density: overrides.density || base.defaults.density, logoScale: overrides.logoScale ?? LOGO_SCALE_DEFAULT }; }
export function getResolvedTypography(policy: Pick<Policy, "documentTemplate" | "documentTheme" | "documentThemeOverrides" | "templateBrandOverrides" | "typography">): DocumentTypography { const themeTypography = getPolicyDocumentTheme(policy).defaults.typography; return { ...themeTypography, ...policy.typography, headingFontFamily: policy.typography?.headingFontFamily || themeTypography.headingFontFamily }; }
export function getDocumentThemePatch(id: DocumentTemplateId): Pick<Policy, "documentTemplate" | "documentTheme" | "documentThemeOverrides" | "templateBrandOverrides" | "typography" | "visualStyle" | "logoPosition" | "sdgDisplay"> { const selected = getDocumentTheme(id); return { documentTemplate: selected.id, documentTheme: selected.id, documentThemeOverrides: undefined, templateBrandOverrides: undefined, typography: { ...selected.defaults.typography }, visualStyle: selected.defaults.visualStyle, logoPosition: selected.defaults.logoPosition, sdgDisplay: selected.defaults.sdgDisplay }; }
export function getDocumentTemplatePatch(id: DocumentTemplateId, policy?: Pick<Policy, "documentThemeOverrides" | "templateBrandOverrides" | "typography" | "visualStyle" | "logoPosition" | "sdgDisplay">, opts: { resetBrand?: boolean } = {}): Pick<Policy, "documentTemplate" | "documentTheme" | "documentThemeOverrides" | "templateBrandOverrides" | "typography" | "visualStyle" | "logoPosition" | "sdgDisplay"> { const selected = getDocumentTheme(id); if (opts.resetBrand) return getDocumentThemePatch(selected.id); const currentBase = policy ? getDocumentTheme((policy as Policy).documentTemplate ?? (policy as Policy).documentTheme) : undefined; const hasManualTypography = Boolean(policy?.typography && currentBase && JSON.stringify(policy.typography) !== JSON.stringify(currentBase.defaults.typography)); return { documentTemplate: selected.id, documentTheme: selected.id, ...(policy?.templateBrandOverrides !== undefined || policy?.documentThemeOverrides !== undefined ? { documentThemeOverrides: policy?.documentThemeOverrides, templateBrandOverrides: policy?.templateBrandOverrides } : {}), typography: hasManualTypography ? { ...policy!.typography! } : { ...selected.defaults.typography }, ...(policy?.visualStyle !== undefined ? { visualStyle: policy.visualStyle } : {}), ...(policy?.logoPosition !== undefined ? { logoPosition: policy.logoPosition } : {}), ...(policy?.sdgDisplay !== undefined ? { sdgDisplay: policy.sdgDisplay } : {}) }; }
export function isDocumentThemeCustomized(policy: Policy): boolean { const selected = getPolicyDocumentTheme(policy); const typography = getResolvedTypography(policy); const defaults = selected.defaults.typography; return Boolean(policy.documentThemeOverrides ?? policy.templateBrandOverrides) || policy.visualStyle !== selected.defaults.visualStyle || policy.logoPosition !== selected.defaults.logoPosition || policy.sdgDisplay !== selected.defaults.sdgDisplay || typography.fontFamily !== defaults.fontFamily || typography.headingFontFamily !== defaults.headingFontFamily || typography.headingSize !== defaults.headingSize || typography.subheadingSize !== defaults.subheadingSize || typography.paragraphSize !== defaults.paragraphSize || typography.lineSpacing !== defaults.lineSpacing; }
export function documentThemeCssVariables(selected: DocumentThemeDefinition): Record<string, string> { const resolved = "background" in selected ? selected as ResolvedDocumentThemeDefinition : { ...selected, background: defaultThemeBackground(selected), density: selected.defaults.density, logoScale: LOGO_SCALE_DEFAULT }; const logo = runningLogoFit(resolved.logoScale); return { "--doc-primary": selected.colors.primary, "--doc-primary-dark": selected.colors.primaryDark, "--doc-subheading": selected.colors.subheading, "--doc-soft": selected.colors.soft, "--doc-paper": selected.colors.paper, "--doc-ink": selected.colors.ink, "--doc-muted": selected.colors.muted, "--doc-line": selected.colors.line, "--doc-accent": selected.colors.accent, "--doc-on-primary": selected.colors.onPrimary, "--doc-page-background": themeBackgroundCss(resolved.background), "--doc-density-factor": resolved.density === "compact" ? ".82" : resolved.density === "spacious" ? "1.18" : "1", "--doc-logo-height": `${72 * logoScaleFactor(resolved.logoScale)}px`, "--doc-running-logo-height": `${logo.heightPx}px`, "--doc-running-logo-width": `${logo.widthPx}px` }; }
export function defaultThemeBackground(selected: DocumentThemeDefinition): ThemeBackground { return { kind: "solid", color: selected.colors.paper }; }
export function themeBackgroundCss(background: ThemeBackground): string { if (background.kind === "solid") return background.color; const direction = background.direction === "horizontal" ? "90deg" : background.direction === "vertical" ? "180deg" : "135deg"; return `linear-gradient(${direction}, ${background.from}, ${background.to})`; }
export function normalizeHexColor(value: unknown): string | null { if (typeof value !== "string") return null; const trimmed = value.trim(); return /^#[0-9a-f]{6}$/i.test(trimmed) ? trimmed.toUpperCase() : null; }
function blendHex(first: string, second: string, amount: number): string { const parse = (value: string) => value.slice(1).match(/.{2}/g)!.map((channel) => Number.parseInt(channel, 16)); const [r1, g1, b1] = parse(first); const [r2, g2, b2] = parse(second); return `#${[r1, g1, b1].map((channel, index) => Math.round(channel + ([r2, g2, b2][index] - channel) * amount).toString(16).padStart(2, "0")).join("")}`.toUpperCase(); }
export function normalizeDocumentThemeOverrides(value: unknown): DocumentThemeOverrides { const raw = value && typeof value === "object" ? value as Partial<DocumentThemeOverrides> : {}; const paletteKeys = new Set<keyof DocumentThemePalette>(["primary", "primaryDark", "subheading", "soft", "paper", "ink", "muted", "line", "accent", "onPrimary"]); const colors = raw.colors && typeof raw.colors === "object" ? Object.fromEntries(Object.entries(raw.colors).filter(([key]) => paletteKeys.has(key as keyof DocumentThemePalette)).map(([key, color]) => [key, normalizeHexColor(color)]).filter((entry): entry is [string, string] => Boolean(entry[1]))) as Partial<DocumentThemePalette> : undefined; let background: ThemeBackground | undefined; if (raw.background?.kind === "solid") { const color = normalizeHexColor(raw.background.color); if (color) background = { kind: "solid", color }; } else if (raw.background?.kind === "gradient") { const from = normalizeHexColor(raw.background.from); const to = normalizeHexColor(raw.background.to); const direction = ["vertical", "horizontal", "diagonal"].includes(raw.background.direction) ? raw.background.direction : "diagonal"; if (from && to) background = { kind: "gradient", from, to, direction }; } const logoScale = typeof raw.logoScale === "number" && Number.isFinite(raw.logoScale) ? Math.min(LOGO_SCALE_MAX, Math.max(LOGO_SCALE_MIN, Math.round(raw.logoScale))) : typeof raw.logoScale === "string" && ["small", "medium", "large"].includes(raw.logoScale) ? raw.logoScale as LogoScale : undefined; return { schemaVersion: 1, ...(raw.pageBorder ? { pageBorder: normalizePageBorder(raw.pageBorder) } : {}), ...(typeof raw.customThemeName === "string" && raw.customThemeName.trim() ? { customThemeName: raw.customThemeName.trim().slice(0, 60) } : {}), ...(colors && Object.keys(colors).length ? { colors } : {}), ...(background ? { background } : {}), ...(["compact", "balanced", "spacious"].includes(raw.density || "") ? { density: raw.density } : {}), ...(logoScale !== undefined ? { logoScale } : {}) }; }
export const normalizeTemplateBrandOverrides = normalizeDocumentThemeOverrides;
export function getFullThemeOverrides(policy: Policy, customThemeName?: string): DocumentThemeOverrides { const selected = getPolicyDocumentTheme(policy); return { schemaVersion: 1, ...(customThemeName ? { customThemeName } : {}), pageBorder: { ...selected.pageBorder }, colors: { ...selected.colors }, background: structuredClone(selected.background), density: selected.density, logoScale: selected.logoScale }; }
export const getFullBrandOverrides = getFullThemeOverrides;
export function documentHex(color: string): string { return color.replace(/^#/, "").toUpperCase(); }
export function pdfFontFamily(fontFamily?: string): "Helvetica" | "Times-Roman" | "Courier" { if (!fontFamily) return "Helvetica"; if (/courier|mono/i.test(fontFamily)) return "Courier"; if (/cambria|georgia|garamond|times/i.test(fontFamily)) return "Times-Roman"; return "Helvetica"; }

/** Restore the selected source palette without resetting typography, borders or backgrounds. */
export function getPolicyColorResetPatch(policy: DocumentThemePolicyInput): Pick<Policy, "documentThemeOverrides" | "templateBrandOverrides"> {
  const overrides = normalizeDocumentThemeOverrides(policy.templateBrandOverrides ?? policy.documentThemeOverrides);
  const reset = { ...overrides, colors: undefined };
  return { documentThemeOverrides: reset, templateBrandOverrides: reset };
}
