"use client";
import { useBuilder } from "@/lib/store";
import { Input, Textarea } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { List, ListOrdered, Plus, Table2, Trash2, Type } from "lucide-react";
import type { RichTextBlock } from "@/lib/types";

const makeBlock = (sectionId: string, type: RichTextBlock["type"]): RichTextBlock => ({ id: `${sectionId}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, type, text: "", ...(type === "table" ? { columns: ["Column 1", "Column 2"], rows: [["", ""]] } : {}) });

export function StepCustom() {
  const { policy, updatePolicy } = useBuilder();
  const custom = (policy.sections || []).filter((s) => s.kind === "custom" && s.enabled);
  const updateBlock = (sectionId: string, blockId: string, patch: Partial<RichTextBlock>) => updatePolicy((p) => ({ sections: (p.sections || []).map((s) => s.id !== sectionId ? s : { ...s, blocks: (s.blocks || []).map((b) => b.id === blockId ? { ...b, ...patch } : b) }) }));
  const removeBlock = (sectionId: string, blockId: string) => updatePolicy((p) => ({ sections: (p.sections || []).map((s) => s.id !== sectionId ? s : { ...s, blocks: (s.blocks || []).filter((b) => b.id !== blockId) }) }));
  const addBlock = (sectionId: string, type: RichTextBlock["type"]) => updatePolicy((p) => ({ sections: (p.sections || []).map((s) => s.id !== sectionId ? s : { ...s, blocks: [...(s.blocks || []), makeBlock(sectionId, type)] }) }));
  const updateCell = (sectionId: string, block: RichTextBlock, row: number, column: number, value: string) => { const rows = (block.rows || []).map((r) => [...r]); rows[row][column] = value; updateBlock(sectionId, block.id, { rows }); };
  const addRow = (sectionId: string, block: RichTextBlock) => updateBlock(sectionId, block.id, { rows: [...(block.rows || []), (block.columns || []).map(() => "")] });
  const addColumn = (sectionId: string, block: RichTextBlock) => updateBlock(sectionId, block.id, { columns: [...(block.columns || []), `Column ${(block.columns?.length || 0) + 1}`], rows: (block.rows || []).map((row) => [...row, ""]) });
  const removeRow = (sectionId: string, block: RichTextBlock, index: number) => updateBlock(sectionId, block.id, { rows: (block.rows || []).filter((_, i) => i !== index) });
  const removeColumn = (sectionId: string, block: RichTextBlock, index: number) => updateBlock(sectionId, block.id, { columns: (block.columns || []).filter((_, i) => i !== index), rows: (block.rows || []).map((row) => row.filter((_, i) => i !== index)) });
  return <div className="space-y-7">{custom.map((section) => <div key={section.id} className="bg-[var(--color-paper)] border border-[var(--color-line)] rounded-xl p-5"><h2 className="font-display text-[21px] font-semibold">{section.title}</h2><div className="mt-4 space-y-4">{(section.blocks || []).map((block) => <div key={block.id} className="rounded-xl border border-[var(--color-line)] bg-white p-3"><div className="mb-2 flex items-center justify-between gap-3"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-[var(--color-muted)]">{block.type === "table" ? "Table" : "Content block"}</span><button onClick={() => removeBlock(section.id, block.id)} className="inline-flex h-7 items-center gap-1.5 rounded-md px-2 text-[11px] font-medium text-[var(--color-muted)] transition-colors hover:bg-red-50 hover:text-red-700" aria-label="Delete block" title="Delete block"><Trash2 size={13}/><span>Delete</span></button></div>{block.type === "table" ? <TableEditor block={block} sectionId={section.id} updateBlock={updateBlock} updateCell={updateCell} addRow={addRow} addColumn={addColumn} removeRow={removeRow} removeColumn={removeColumn}/> : <><select value={block.type} onChange={(e) => updateBlock(section.id, block.id, { type: e.target.value as RichTextBlock["type"] })} className="mb-2 h-8 rounded-md border border-[var(--color-line-2)] bg-[var(--color-cream)] px-2.5 text-[11px] font-medium text-[var(--color-ink-2)] outline-none focus:border-[var(--color-forest)]"><option value="paragraph">Paragraph</option><option value="bullets">Bulleted list</option><option value="numbered">Numbered list</option></select><Textarea value={block.text} rows={block.type === "paragraph" ? 4 : 3} onChange={(e) => updateBlock(section.id, block.id, { text: e.target.value })} placeholder={block.type === "paragraph" ? "Write a paragraph…" : "One item per line…"}/></>}</div>)}</div><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" size="sm" icon={<Type size={13}/>} onClick={() => addBlock(section.id, "paragraph")}>Paragraph</Button><Button variant="secondary" size="sm" icon={<List size={13}/>} onClick={() => addBlock(section.id, "bullets")}>Bullets</Button><Button variant="secondary" size="sm" icon={<ListOrdered size={13}/>} onClick={() => addBlock(section.id, "numbered")}>Numbered</Button><Button variant="secondary" size="sm" icon={<Table2 size={13}/>} onClick={() => addBlock(section.id, "table")}>Add table</Button></div></div>)}</div>;
}

function TableEditor({ block, sectionId, updateBlock, updateCell, addRow, addColumn, removeRow, removeColumn }: { block: RichTextBlock; sectionId: string; updateBlock: (sectionId: string, blockId: string, patch: Partial<RichTextBlock>) => void; updateCell: (sectionId: string, block: RichTextBlock, row: number, column: number, value: string) => void; addRow: (sectionId: string, block: RichTextBlock) => void; addColumn: (sectionId: string, block: RichTextBlock) => void; removeRow: (sectionId: string, block: RichTextBlock, index: number) => void; removeColumn: (sectionId: string, block: RichTextBlock, index: number) => void; }) {
  const columns = block.columns || []; const rows = block.rows || [];
  return <div className="pr-7"><div className="mb-3 text-[11px] uppercase tracking-wider font-semibold text-[var(--color-muted)]">Custom table</div><div className="overflow-x-auto border border-[var(--color-line)]"><table className="min-w-full text-[12px]"><thead className="bg-[var(--color-cream)]"><tr>{columns.map((column, index) => <th key={index} className="min-w-[150px] p-2 border-r border-[var(--color-line)]"><div className="flex gap-1"><Input value={column} onChange={(e) => { const next = [...columns]; next[index] = e.target.value; updateBlock(sectionId, block.id, { columns: next }); }} className="h-7 text-[11px] font-semibold bg-white"/><button onClick={() => removeColumn(sectionId, block, index)} disabled={columns.length <= 1} className="text-[var(--color-muted)] hover:text-red-700 disabled:opacity-30" aria-label="Remove column"><Trash2 size={12}/></button></div></th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex} className="border-t border-[var(--color-line)]">{columns.map((_, columnIndex) => <td key={columnIndex} className="p-1.5 border-r border-[var(--color-line)]"><Input value={row[columnIndex] || ""} onChange={(e) => updateCell(sectionId, block, rowIndex, columnIndex, e.target.value)} className="h-8 text-[11px] border-transparent bg-transparent focus:bg-white"/></td>)}<td className="p-1 text-center"><button onClick={() => removeRow(sectionId, block, rowIndex)} disabled={rows.length <= 1} className="text-[var(--color-muted)] hover:text-red-700 disabled:opacity-30" aria-label="Remove row"><Trash2 size={13}/></button></td></tr>)}</tbody></table></div><div className="mt-3 flex gap-2"><Button variant="secondary" size="sm" icon={<Plus size={12}/>} onClick={() => addRow(sectionId, block)}>Add row</Button><Button variant="secondary" size="sm" icon={<Plus size={12}/>} onClick={() => addColumn(sectionId, block)}>Add column</Button></div></div>;
}
