"use client";
import { getCompanySites, type Policy, type RichTextBlock } from "@/lib/types";
import { getEnabledSections } from "@/lib/sections";
import { SDG_DATA, FRAMEWORK_ALIGNMENT, getPolicyProfile } from "@/lib/constants";

const Paras = ({ text }: { text: string }) => <>{text.split(/\r?\n+/).filter(Boolean).map((p, i) => <p key={i} className="text-[13px] leading-[1.8] text-[#1f1f1f] text-justify mb-3 last:mb-0">{p}</p>)}</>;
const Blocks = ({ blocks = [] }: { blocks?: RichTextBlock[] }) => <>{blocks.map((block) => {
  if (block.type === "paragraph") return <Paras key={block.id} text={block.text}/>;
  if (block.type === "table") return <div key={block.id} className="overflow-hidden border border-[var(--color-line)] mb-4"><table className="w-full text-[12px]"><thead className="bg-[#f3eee3]"><tr>{(block.columns || []).map((column, i) => <th key={i} className="p-2 text-left font-bold">{column}</th>)}</tr></thead><tbody>{(block.rows || []).map((row, i) => <tr key={i} className="border-t border-[var(--color-line)]">{(block.columns || []).map((_, j) => <td key={j} className="p-2 align-top">{row[j]}</td>)}</tr>)}</tbody></table></div>;
  return <ol key={block.id} className={block.type === "bullets" ? "list-disc pl-5 space-y-1.5 mb-3" : "list-decimal pl-5 space-y-1.5 mb-3"}>{block.text.split(/\r?\n+/).filter(Boolean).map((x, i) => <li key={i} className="text-[13px] leading-[1.7]">{x}</li>)}</ol>;
})}</>;

export function PolicyPreview({ policy }: { policy: Policy }) {
  const co = policy.company; const profile = getPolicyProfile(policy.policyType); const sections = getEnabledSections(policy); const sites = getCompanySites(co);
  const quant = policy.quantitative.filter((q) => q.targets.some((t) => t.target)); const qual = Object.entries(policy.qualitative).filter(([, v]) => v.length);
  return <article className="bg-white shadow-[0_16px_45px_rgba(42,50,42,.13)] max-w-4xl mx-auto text-[var(--color-ink)]">
    <header className="px-10 py-12 border-b-2 border-[var(--color-forest)] text-center"><div className="text-[10px] tracking-[.23em] text-[var(--color-forest)] font-bold">SUSTAINABILITY POLICY</div><h1 className="font-display text-[34px] font-semibold mt-3">{profile.label}</h1><p className="text-[15px] text-[var(--color-muted)] mt-2">{co.name || "[Company Name]"}</p><div className="grid grid-cols-2 sm:grid-cols-4 text-left border border-[var(--color-forest)] mt-8 text-[10px]"><Meta label="Document No." value={co.docNum}/><Meta label="Effective Date" value={co.effectiveDate}/><Meta label="Revision" value={co.revNum || "01"}/><Meta label="Next Review" value={co.reviewDate}/></div></header>
    {policy.showTableOfContents && <section className="px-10 py-9 border-b border-[var(--color-line)]"><Heading>Table of Contents</Heading><ol className="mt-5 space-y-2">{sections.map((s,i)=><li key={s.id} className="flex gap-3 text-[12.5px]"><b className="font-mono text-[var(--color-forest)]">{String(i+1).padStart(2,"0")}</b>{s.title}</li>)}{policy.showAcknowledgement && <li className="flex gap-3 text-[12.5px]"><b className="font-mono text-[var(--color-forest)]">{String(sections.length+1).padStart(2,"0")}</b>Employee Acknowledgement Form</li>}</ol></section>}
    <main className="px-10 py-10 space-y-9">{sections.map((s) => <section key={s.id}><Heading>{s.title}</Heading>{renderSection(s.kind, policy, sites, qual, quant, s.blocks)}</section>)}</main>
    <footer className="px-10 py-6 border-t-2 border-[var(--color-forest)] text-[11px] text-[var(--color-muted)] flex justify-between"><span>Effective Date: {co.effectiveDate || "—"}</span><span>Approved by: {co.approver || "_____________________"}</span><span>Revision: {co.revNum || "01"}</span></footer>
    {policy.showAcknowledgement && <section className="px-10 py-9 bg-[#fbf9f3] border-t border-dashed border-[var(--color-line)]"><h3 className="font-display text-[18px] font-semibold text-center">Employee Acknowledgement Form</h3><p className="mt-4 text-[12.5px] leading-[1.7]">I acknowledge that I have read and understood this policy and agree to uphold its commitments in my work.</p><div className="grid grid-cols-2 gap-x-8 gap-y-5 mt-6">{["Employee Name","Employee ID","Department","Date"].map(x=><div key={x}><div className="text-[9px] uppercase tracking-wider text-[var(--color-muted)]">{x}</div><div className="h-7 border-b border-[#aaa]"/></div>)}</div></section>}
  </article>;
}
function Meta({label,value}:{label:string,value?:string}){return <div className="p-2.5 border-r last:border-0 border-[var(--color-forest)]"><div className="font-bold text-[9px] text-[var(--color-forest)]">{label}</div><div className="mt-1">{value||"—"}</div></div>}
function Heading({children}:{children:React.ReactNode}){return <h2 className="font-sans text-[12px] font-bold uppercase tracking-[.14em] text-[var(--color-forest)] pb-2 border-b border-[#c8e2d2] mb-4">{children}</h2>}
function renderSection(kind:string, policy:Policy, sites:ReturnType<typeof getCompanySites>, qual:[string,string[]][], quant:Policy["quantitative"], blocks?:RichTextBlock[]){
 switch(kind){
  case "preface": return <Paras text={policy.declaration.preface}/>; case "declaration": return <Paras text={policy.declaration.declaration}/>; case "scope": return <><Paras text={policy.declaration.scope}/>{sites.length>0&&<div className="mt-4 overflow-hidden border border-[var(--color-line)] font-sans"><table className="w-full text-left text-[11px]"><thead className="bg-[#f3eee3] text-[var(--color-ink-2)]"><tr><th className="px-3 py-2 font-bold w-[24%]">Location / Unit</th><th className="px-3 py-2 font-bold">Address</th><th className="px-3 py-2 font-bold w-[24%]">Primary Function</th></tr></thead><tbody>{sites.map((s,i)=><tr key={i} className="border-t border-[var(--color-line)]"><td className="px-3 py-2 font-semibold align-top">{s.location||`Site ${i+1}`}</td><td className="px-3 py-2 align-top">{s.address}</td><td className="px-3 py-2 align-top text-[var(--color-muted)]">{s.primaryFunction||"Operating Site"}</td></tr>)}</tbody></table></div>}</>;
  case "definitions": return <Paras text={policy.definitions?.content||""}/>; case "framework": return <ul className="space-y-2">{policy.standards.filter(s=>FRAMEWORK_ALIGNMENT[s]).map(s=><li key={s} className="text-[13px]"><b>{s}:</b> {FRAMEWORK_ALIGNMENT[s]}</li>)}</ul>;
  case "focus": return policy.visualStyle === "corporate" ? <table className="w-full text-[12px] border border-[var(--color-line)]"><tbody>{policy.focusAreas.filter(Boolean).map((a,i)=><tr key={a}><td className="p-2 border-b w-10 font-bold">{i+1}</td><td className="p-2 border-b">{a}</td></tr>)}</tbody></table> : <ul className="list-disc pl-5 space-y-2">{policy.focusAreas.filter(Boolean).map(a=><li key={a} className="text-[13px]">{a}</li>)}</ul>;
  case "qualitative": return <div className="space-y-4">{qual.map(([a,items])=><div key={a}><b className="text-[13px]">{a}</b><ul className="list-disc pl-5 mt-1 space-y-1">{items.map(x=><li key={x} className="text-[13px]">{x}</li>)}</ul></div>)}</div>;
  case "quantitative": return policy.visualStyle === "corporate" ? <table className="w-full text-[11px] border border-[var(--color-line)]"><thead><tr className="bg-[var(--color-forest)] text-white"><th className="p-2 text-left">Area</th><th className="p-2 text-left">Target</th><th className="p-2 text-left">Deadline</th></tr></thead><tbody>{quant.flatMap(q=>q.targets.filter(t=>t.target).map(t=><tr key={`${q.area}${t.target}`}><td className="p-2 border-t">{q.area}</td><td className="p-2 border-t">{t.target}</td><td className="p-2 border-t">{t.reportingFrequency==="Annually"?"Annually":t.deadline}</td></tr>))}</tbody></table> : <div className="space-y-3">{quant.map(q=><div key={q.area}><b className="text-[13px]">{q.area}</b>{q.targets.filter(t=>t.target).map(t=><p key={t.target} className="text-[13px] mt-1">• {t.target}{t.deadline&&` (${t.deadline})`}</p>)}</div>)}</div>;
  case "sdg": return policy.sdgDisplay === "tiles" ? <div className="flex flex-wrap gap-3">{policy.sdgs.map(n => { const s = SDG_DATA.find(x => x.n === n)!; const goal = String(n).padStart(2, "0"); return <img key={n} src={`/E%20SDG%20Icons%20WEB/E-WEB-Goal-${goal}.png`} alt={`UN Sustainable Development Goal ${n}: ${s.label}`} className="w-[92px] h-[92px] object-cover" />; })}</div> : <div className="flex flex-wrap gap-2">{policy.sdgs.map(n=>{const s=SDG_DATA.find(x=>x.n===n)!;return <span key={n} className="inline-flex items-center gap-1.5 px-2 py-1 text-[11px] font-semibold" style={{background:s.c,color:"white"}}>SDG {n}: {s.label}</span>})}</div>;
  case "responsibilities": return policy.visualStyle === "corporate" ? <table className="w-full text-[12px] border border-[var(--color-line)]"><tbody>{policy.responsibilities.map(r=><tr key={r.role}><td className="p-2 border-b font-bold w-1/3">{r.role}</td><td className="p-2 border-b">{r.duty}</td></tr>)}</tbody></table> : <ul className="space-y-2">{policy.responsibilities.map(r=><li key={r.role} className="text-[13px]"><b>{r.role}:</b> {r.duty}</li>)}</ul>;
  case "monitoring": return <Paras text={policy.monitoring}/>; case "review": return <Paras text={policy.reviewMechanism}/>; case "custom": return <Blocks blocks={blocks}/>; default:return null;
 }}
